name: Publish
"on":
  push:
    branches:
      - main
      - beta
    # paths:
    #   - RELEASES.md
jobs:
  Release:
    name: 'Release'
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Get version from gen.yaml
          id: get_version
          uses: mikefarah/yq@master
          with:
            cmd: yq '.typescript.version' gen.yaml
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: ${{ steps.get_version.outputs.result }}
            release_name: Release ${{ steps.get_version.outputs.result }}
            draft: false
            prerelease: false

  Publish:
    name: 'Publish'
    needs: 
      - Release
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org'
        - run: npm ci
        - run: npm publish --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
